name: Batch Replace Strings

on:
  workflow_dispatch:

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 移动 app/src/main/java/com/github/tvbox/osc 路径中的文件到新的文件夹 spiderbox
      - name: Move files from /app/src/main/java/com/github/tvbox/osc to /spiderbox
        run: |
          # 创建目标文件夹
          mkdir -p spiderbox

          # 检查路径是否存在，若存在，则移动文件
          if [ -d "app/src/main/java/com/github/tvbox/osc" ]; then
            mv app/src/main/java/com/github/tvbox/osc/* spiderbox/
            # 如果有子目录，需要递归处理
            find app/src/main/java/com/github/tvbox/osc -type d -exec mv {} spiderbox/ \;
          else
            echo "Directory app/src/main/java/com/github/tvbox/osc does not exist or is empty."
          fi

      # 替换所有文件中的 "tvbox.osc" 为 "spiderbox"
      - name: Replace strings in files
        run: |
          find . -type f -exec sed -i 's/tvbox.osc/spiderbox/g' {} +

      # 提交更改，避免推送工作流文件
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 删除工作流文件夹，确保不会推送工作流文件的更改
          rm -rf .github/workflows
          
          git add --all  # 添加所有文件
          git diff --cached --name-only | grep -v '^\.github/workflows/' | xargs git add  # 排除工作流文件
          git commit -m "Move files and replace 'tvbox.osc' with 'spiderbox'"
          git push
